[format]
indent_style = "space"
indent_size = 2
line_width = 100
quote_style = "double"
trailing_comma = "all"

[linter]
enabled = true

[linter.rules]
semi = "always"
quotes = "double"

[exclude]
paths = ["node_modules", ".next", "dist", "out", "public"]

[files]
includes = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"]
excludes = ["node_modules/**", ".next/**"]
maxSize = "10mb"
