name: CI / Biome + Vercel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Biome check
        run: npx biome check || true

      - name: Vercel Deploy
        uses: nexterias/actions-vercel@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          cwd: .               # working-directory の代わり
          production: true     # prod の代わり
          github-token: ${{ secrets.GITHUB_TOKEN }} # 推奨
